name: WildPE
main: WildPE\wild
api: [3.0.0-ALPHA12]
author: VMPE Development Team
description: WildPE
commands:
     wild:
     description: Teleport to a random spot.
permissions:
     wild.command:
         default: true
