name: WildPE
main: WildPE\wild
version: 1.0.0-BETA1
api: [3.0.0-ALPHA12]
author: VMPE Development Team
description: WildPE plugin.
commands:
     wild:
     description: Teleport to a random spot.
     usage: /wild
permissions:
     wild.command:
         default: true
